<?php
use \Drupal\node\Entity;

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function sachlife_content_theme($existing, $type, $theme, $path) {
  return array(
    'homepage' => array(
      'variables'=> array('content'=>[]),
    ),
    'ourstory' => array(
      'variables'=> array('content' => []),
    ),
    'aboutme' => array(
      'variables'=> array('content' => []),
    ),
    'blogPost' => array(
      'variables'=> array('content' => []),
    ),
    'blogList' => array(
      'variables'=> array('content' => []),
    ),
    'headerimage' => array(
      'variables'=> array('content' => ''),
    ),
    'recentposts' => array(
      'variables'=> array('content' => []),
    ),
  );
}

/**
 * Implements hook_page_attachments().
 */
function sachlife_content_page_attachments(array &$page) {
  $parameters = \Drupal::routeMatch()->getParameters();
  $nid = $parameters->get('nid');
  if($nid){
    $nodeDetails = Entity\Node::load($nid);
    $descriptionValue = $nodeDetails->get('body')->summary;
    $contentValue = $nodeDetails->getTitle();
  }else{
    $descriptionValue = 'This is my site';
    $contentValue = 'Chambu Bambu';
  }
  $description = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'description',
      'content' => $descriptionValue,
    ],
  ];
  $title = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'title',
      'content' => $contentValue,
    ],
  ];
  $page['#attached']['html_head'][] = [$description, 'description'];
  $page['#attached']['html_head'][] = [$title, 'title'];
}

/**
 * @param $account
 * Hook User login for redirection after login
 * User will redirect to Administrator page
 */
function sachlife_content_user_login($account) {
  global $base_url;
  $url = $base_url.'/admin';
  $response = new Symfony\Component\HttpFoundation\RedirectResponse($url);
  $response->send();
  return;
}